### ISSUE TITLE
Fullscreen error

### ISSUE THREAD

**Issue by tobenaii** [MediaBrowser/Emby#3549] opened 2019-04-28 11:39 UTC
When I try to fullscreen a video, chrome spits this error and does nothing.
![Screenshot_23](https://user-images.githubusercontent.com/30368443/56863780-eae48d00-69fd-11e9-93a0-0ddc2a9872bb.png)

**Comment by LukePulverenti** [comment] 2019-05-11 18:31
Hi, what version of Chrome?

**Comment by LukePulverenti** [comment] 2019-06-12 03:05
I'm not able to reproduce this. Are you still seeing this?

**Comment by LukePulverenti** [comment] 2019-07-26 16:37
Closing, but please feel free to re-open with the requested information. I have not been able to reproduce this.

**Closed as completed by LukePulverenti** 2019-07-26 16:37 UTC
