### ISSUE TITLE
Binding to a specific address does not work - Emby still listens everywhere

### ISSUE THREAD

**Issue by netvl** [MediaBrowser/Emby#3000] opened 2017-11-02 19:45 UTC
I want my server to expose as little ports to the external world as possible, and I intend to use Emby in my local network onlt. Therefore I configured Emby to bind to 192.168.1.1 (which is the address of my server in the local network): 
```
> grep -A2 '<LocalNetworkAddresses>' /var/lib/emby/config/system.xml
  <LocalNetworkAddresses>
    <string>192.168.1.1</string>
  </LocalNetworkAddresses>
```
However, after restart it still listens on all interfaces:
```
> sudo netstat -ltnp | grep mono
tcp6       0      0 :::8920                 :::*                    LISTEN      4882/mono           
tcp6       0      0 :::8096                 :::*                    LISTEN      4882/mono  
```
And it still shows my external IP address on the dashboard.

As a side question, is it possible to limit addresses on which Emby listens for UDP packets?
```
> sudo netstat -lunp | grep mono
udp        0      0 0.0.0.0:7359            0.0.0.0:*                           4882/mono           
udp        0      0 127.0.0.1:46349         0.0.0.0:*                           4882/mono           
udp        0      0 0.0.0.0:42274           0.0.0.0:*                           4882/mono           
udp        0      0 192.168.1.1:46648       0.0.0.0:*                           4882/mono           
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           4882/mono           
udp        0      0 10.8.0.3:57861          0.0.0.0:*                           4882/mono           
udp        0      0 <my ext addr>:51949     0.0.0.0:*                           4882/mono
```
I can block connections on these ports with iptables, I suppose, but I would prefer it not to listen anywhere except 192.168.1.1. Also, is there somewhere an explanation what these ports are needed for? I prefer having complete knowledge of what programs I install on my servers do, especially when they open ports to the outer world.

**Comment by LukePulverenti** [comment] 2017-11-02 19:48
This is by design. We only use it as a filter, it doesn't influence the binding.

Reason being it's just easier for us because then we need separate sockets for whatever address you enter, another one for localhost, etc.

And then if we do that, then we have to start troubleshooting what happens if one of them fails to bind and the other succeeds, and how we're going to have the server react to that. So that is why we've done it this way.

**Comment by LukePulverenti** [comment] 2017-11-10 18:23
Closing due to expected behavior.

**Closed by LukePulverenti** 2017-11-10 18:23 UTC

**Comment by genofire** [comment] 2017-11-24 15:45
I still can use the webinterface on other address then LocalNetworkAddresses
