### ISSUE TITLE
[Bug] Playback and Transcoding possible although not allowed by admin

### ISSUE THREAD

**Issue by horstepipe** [MediaBrowser/Emby#1815] opened 2016-06-06 15:58 UTC
the option "allow playback that requires transcoding" doesn't seem to work anymore in Emby web client. I disabled it for all my users because my hardware hasn't enough power to transcode.
However the users are able to start a video where I can see in Server dashboard that it is streamed transcoded.
On IOS app it works normally, the users get an error message when the content had to be transcoded.

Also I created a user who should only be allowed to download media, not to play it back.
Unfortunately this doesn't work, the play symbol is still available on the covers and playback still works fine.

**Comment by LukePulverenti** [comment] 2016-06-07 06:42
Duplicate of #1618
https://github.com/MediaBrowser/Emby/issues/1618

**Closed by LukePulverenti** 2016-06-07 06:42 UTC
