### ISSUE TITLE
Cannot Access Server

### ISSUE THREAD

**Issue by randomjzy** [MediaBrowser/Emby#3761] opened 2023-01-02 06:33 UTC
Hi all, I have a AS6602T Asustor server, I cannot access the emby server. I have uninstalled and reinstalled it several times. 
The emby server apk file names "emby-server-asustor_4.8.0.21_x86-64.apk", my router is Huawei AX6. And the other applications works well on my nas, such like Plex. What can i do?

![1](https://user-images.githubusercontent.com/82503095/210200620-c5f6f250-385e-4f5b-b04c-0a2d8dbe96f4.png)
![2](https://user-images.githubusercontent.com/82503095/210200647-db3
![3](https://user-images.githubusercontent.com/82503095/210200656-3c8897a3-d32b-40b8-a626-0e1a85ff03b1.png)
25c6c-ea29-46b9-b6af-85a63454e8cc.png)

Here is the log files:
[hardware_detection-63808263463.txt](https://github.com/MediaBrowser/Emby/files/10330243/hardware_detection-63808263463.txt)
[embyserver.txt](https://github.com/MediaBrowser/Emby/files/10330244/embyserver.txt)

**Comment by randomjzy** [comment] 2023-01-02 06:34
![3](https://user-images.githubusercontent.com/82503095/210200729-caf0647d-aad0-412d-bf4e-789bd8fa0435.png)

**Comment by LukePulverenti** [comment] 2023-01-02 06:35
Hi there, what exactly happens when you try?

**Comment by randomjzy** [comment] 2023-01-02 06:35
![2](https://user-images.githubusercontent.com/82503095/210200764-05c706bd-51a4-4484-baa0-94ad618de5b8.png)

**Comment by randomjzy** [comment] 2023-01-02 06:36
> 

Unable to connect

Firefox can’t establish a connection to the server at 192.168.3.66:8096.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

**Comment by LukePulverenti** [comment] 2023-01-02 06:37
OK, perhaps try uninstalling, then deleting the /home/emby folder, and then reinstall from the asustor app store. Please see if that helps. Thanks.

**Comment by randomjzy** [comment] 2023-01-02 06:40
> 
I have tried several times ,i deleted /home/emby, deleted user emby and group emby ,but nothing chaged

**Comment by LukePulverenti** [comment] 2023-01-02 06:41
Can you please try again and then provide a log from the version installed from the store? Thanks.

**Comment by randomjzy** [comment] 2023-01-02 06:58
> 
the version is 4.7.11.0 in the store, i tried , but nothing changed. Here is the log files:
[hardware_detection-63808267979.txt](https://github.com/MediaBrowser/Emby/files/10330339/hardware_detection-63808267979.txt)
[embyserver.txt](https://github.com/MediaBrowser/Emby/files/10330340/embyserver.txt)

**Comment by randomjzy** [comment] 2023-01-02 07:09
Is this the error ?

```
2023-01-02 14:53:02.339 Error HttpClient: <s:Envelope
xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
<errorCode>402</errorCode>
<errorDescription>Invalid Args</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>

2023-01-02 14:53:02.348 Error HttpClient: <s:Envelope
xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
<errorCode>714</errorCode>
<errorDescription>NoSuchEntryInArray</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>
```

**Comment by NicciZar** [comment] 2023-01-24 16:43
Did you recently changed your router / updated router firmware?
Try to connect directly via ethernet cable either to your router and if it doesn't work then directly to your NAS to see where the problem is.

**Comment by LukePulverenti** [comment] 2023-04-12 02:53
@randomjzy ?

**Comment by LukePulverenti** [comment] 2023-10-18 21:32
Closing, but if you're still having an issue then please feel free to reopen with the requested information. Thanks.

**Closed as completed by LukePulverenti** 2023-10-18 21:32 UTC
