### ISSUE TITLE
HLS playback error

### ISSUE THREAD

**Issue by kaithar** [MediaBrowser/Emby#3221] opened 2018-03-31 21:36 UTC
Since the last update I've been having an issue where music playback via the web app stops after some time with the error "HLS Error: Type: mediaError Details: bufferFullError Fatal: false"
Even though it says it isn't fatal, that appears to be the only error on the brower's console.  Any ideas what extra information would be helpful?

**Comment by LukePulverenti** [comment] 2018-03-31 21:42
What last update?

**Comment by kaithar** [comment] 2018-03-31 22:36
3.3.1.0

**Comment by LukePulverenti** [comment] 2018-04-01 15:37
I wouldn't worry about it. The hls library that we're using has very verbose logging to the console.

**Comment by kaithar** [comment] 2018-04-01 18:29
I wouldn't be worried about it if weren't for the issue that playback keeps stopping ;) If it isn't that error then I haven't a clue what is causing it.

**Comment by LukePulverenti** [comment] 2018-04-06 19:25
Can you provide the ffmpeg log? thanks.

**Comment by LukePulverenti** [comment] 2018-04-21 15:31
Are you still seeing this?

**Comment by LukePulverenti** [comment] 2018-05-01 18:35
I'm closing for now because I can't reproduce this,  but please feel free to re-open with the requested information. Thanks !

**Closed by LukePulverenti** 2018-05-01 18:35 UTC

**Comment by kaithar** [comment] 2018-05-10 00:51
Sorry for not responding to this sooner, I went on holiday just after filing it and completely forgot to follow up.

There's nothing in the ffmpeg log to indicate a problem, as in it shows the song fully transcoded.  Something interesting is that I think it might be consistently stopping at the time code 4:26... songs shorter than that play fine.  Seeking around within the song seems to either have no effect or allow it to finish, but I'm not sure what is causing the difference is.
