### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by rofrantz** [MediaBrowser/Emby#3003] opened 2017-11-04 20:58 UTC
I go in a folder with a lot of photos but for the sake simplicity lets say I have 3 jpegs: a, b and c.
If I sort them descebding by name they are rendered correctly as c, b, a.
The pb occurs when I click on the thumbnail to view photo c.jpg and I see actually a.jpg :(

Now to my real case imagibe when u have 3k photos.
PS: this is happening on ubuntu 16 latest version of emby but for a long time ago so its not a recet bug.
In plus it works well with movies but not with the photos.

**Comment by LukePulverenti** [comment] 2017-11-14 07:34
Duplicate of #2999

**Closed by LukePulverenti** 2017-11-14 07:34 UTC

**Comment by rofrantz** [comment] 2018-02-10 19:27
This is not resolved and shoukd be reopened.
If it helps with the testing:
1. just choose a folder with many pictures
2. Change the sorting order (eg: Date descending)
3. Click to see the 1st picture and u'll notice that even if the preview is correct, the fullsize picture is wrong

**Comment by gerrit507** [comment] 2018-03-01 17:09
Do you still have this usse? I can't reproduce this on 3.3.0.3.

**Comment by rofrantz** [comment] 2018-03-01 17:33
I checked last night on Ubuntu after performing the latest updates of course and its still there :(

**Comment by gerrit507** [comment] 2018-03-01 17:37
What kind of library is it? Home videos and photos?

**Comment by gerrit507** [comment] 2018-03-01 17:46
I've tested it with both home videos and photos and type unset library and I still can't reproduce this issue on Windows 10 and Ubuntu 16.04 with version 3.3.0.3.

**Comment by rofrantz** [comment] 2018-03-01 20:06
I have also ubuntu 16.04 and I see I have 3.3.0.0 and i did the apt-get update & upgrade last night.
Could it be that they did not update the repository package maybe since I see that the latest version 3.3.0.4 ?

**Comment by rofrantz** [comment] 2018-03-01 20:07
And yes its a home & video library

**Comment by gerrit507** [comment] 2018-03-01 20:40
Well 3.3.0.0 is the latest stable and 3.3.0.4 is the latest beta... 

Since you talk about repository package: I would guess that you are on the opensuse repo. This would mean you have a mono build. I have a .net core build from the deb package available here. I don't know if it makes any difference in this case, but actually the .net core builds are the way to go, because mono is deprecated.

Furthermore: do those filenames have any special characters like punctuation, umlauts or whatever?

**Comment by rofrantz** [comment] 2018-03-01 20:42
No special names and I've specified I'm on ubuntu 16.04 same as u

**Comment by gerrit507** [comment] 2018-03-01 20:45
Ok...

Because you're getting you're updates with apt it means you have some repo configured. The only repo I know is the opensuse repo which offers mono builds. The deb files you get here are .net core builds... and those are the ones I have installed.

See:
https://software.opensuse.org/download.html?project=home%3Aemby&package=emby-server

**Comment by gerrit507** [comment] 2018-03-01 20:55
Just to double check: downgraded my server to stable version (.net core build) and I don't have the issue. I bet that it is only related to the mono build. 

For installation of emby only refer to this site:
https://emby.media/download.html

and don't use other packages or repos...

**Comment by gerrit507** [comment] 2018-03-01 23:53
By the way: if you really need the mono version for some reason you can get a zip here from github, maybe opensuse has a old build script or whatever...

**Comment by rofrantz** [comment] 2018-03-18 13:16
Updated again @LukePulverenti @gerrit507 emby (which indeed seems a Mono version) on a Ubunu 16 server. And I currently have displayed in the web interface "Version 3.3.1.0".
I've even removed and re-added my Home Videos & Photos library which contains both photos & videos and still, the thumbnail are displayed ok, but when I click to actually see the bigger picture a totally different picture is displayed :(((((((((((((

Can we please re-open this issue ?

**Comment by gerrit507** [comment] 2018-03-18 15:02
This is not an issue as long as you are using a build from an UNOFFICIAL source. Try it with the builds provided by emby directly. If the issue persists then it could be reopened but for now this is just not of our business and beyond the control of the emby team.

**Comment by rofrantz** [comment] 2018-03-18 15:29
Ok so I guess u would recommend the link from https://emby.media/download.html @gerrit507, right ?

**Comment by gerrit507** [comment] 2018-03-18 15:29
Yes.

**Comment by rofrantz** [comment] 2018-03-18 15:54
Do u know if its possible to use the git repo and compile it on ubuntu or is this related to the big GPL licence issue and its not possible ?

Any other proposal for an easy auto update linux repository is also appreciated.

**Comment by linussweden** [comment] 2018-03-19 06:30
This issue does exist in official builds, at least I think so.
I downloaded my emby server from emby website a couple of years ago and installed it on Windows 10. I've had this bug since at least a year back.

I've got my home videos and photos folder sorted by name, descending, no filter, so that the newest photos appears at the top. I've included photos from two phones. These phones sync all of their photos to a single folder each, so I've got two folders included in the library. The folder that contains more than 500 photos is the one giving me problems. 

The photos are shown correctly as previews/thumbs but if I click on them they show the first picture in that folder in fullscreen instead of the correct picture. Only the oldest 500 pictures in that folder works correctly. Any photo but the oldest 500 is affected by the bug. 

I'm running emby server 3.3.1.0 and the bug is in this version. It's been in all updates for as long as I can remember. Perhaps it was once working correctly or I've not had more than 500 photos in a single folder before, I could not tell. I've only updated as far as I can remember from automatic updates that emby server downloads itself.

Or perhaps I'm running an unofficial release and I just don't know it?

The bug is present in both web interface as well as in emby theater for Windows.

**Comment by rofrantz** [comment] 2018-03-19 07:47
...apparently some devs are not capable to send thumbnail photo id and display the full size image of that exact photo.
On the good side they're over qualified for closing reported issues very fast even before they solve them with a futuristic statement "fixed in the next release".

It's been 4 months guys for a very simple problem guys. U dont have time for all reported issues ? Provide the sources so the community devs can help u or rip !

Plex or any other decent app...here I come...

**Comment by gerrit507** [comment] 2018-03-19 18:40
@rofrantz Your description of the issue was with 3 or a couple of images. I've tested this on two systems, ubuntu and windows, and I couldn't reproduce the bug, so the only logic conclusion was that your build is faulty. Now @linussweden says that it only happens with 500+ images, which I didn't have tested. By the way I'm not part of the emby dev team. I'm only a contributer here.

**Comment by rofrantz** [comment] 2018-03-19 20:39
My bad indeed, issue can be closed.

**Comment by rofrantz** [comment] 2018-03-19 20:39
Issue with no of photos = 3 is fixed; 4, 5, 6, ... 500 remaining not to mention that Luke closed it right away as a duplicate of #2999 which has 5 months.

Do I need to open an issue for 501 photos or u finally understood 501+ means 500 or more and I provided a generic example...

**Comment by LukePulverenti** [comment] 2018-03-19 20:43
Hi, no, #2999 is sufficient. Thanks.

**Comment by gerrit507** [comment] 2018-03-19 23:48
"generic example"
3 photos or 500+ is a huge difference...
3 photos would affect nearly everybody, 500+ photos in one folder is very rare border case imho...
