### ISSUE TITLE
Sometimes videos will not load entirely in newer versions of Firefox.

### ISSUE THREAD

**Issue by dkanada** [MediaBrowser/Emby#2990] opened 2017-10-30 09:21 UTC
The video player gets stuck on the background image and the console in Firefox shows the error `HLS Error: Type: networkError Details: fragLoadError Fatal: false` repeating for as long as I have the tab open. I am using a recent version of the server on Linux and Firefox 56. I don't think older versions of of Firefox have this issue, version 52 seems to work fine.

**Comment by LukePulverenti** [comment] 2017-11-02 18:10
I'm not able to reproduce this. Can you please attach the information requested in how to report a media playback issue: https://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks !

**Comment by DomiStyle** [comment] 2017-11-02 21:03
I have experienced this issue multiple times but it's a real pain to reproduce reliably. Sometimes it happens for every file, sometimes it never happens, sometimes it rarely happens.

Screenshots are the last two in [this thread](https://emby.media/community/index.php?/topic/51829-tried-emby-for-one-month/?p=498910).

In Firefox 57 it either is the player on top without controls or the player on top with the spinner animation showing. Can't back out of this state without refreshing.

Had to do quite some switching between different files to get it to happen but I attached a [server log file](https://github.com/MediaBrowser/Emby/files/1439380/server-63645251734.txt). The one that got stuck in the end was "Dead Like Me S1E5" all the others played back fine. Will see if I can get some logs from Firefox the next time it happens.

Some interesting things I noticed: The file will play but it isn't shown in the admin dashboard. Once the file failed to play once it will happen over and over for this file.

Also, Emby does an excellent job otherwise in Firefox 57. Files play quickly and the interface is snappy.

**Comment by dkanada** [comment] 2017-11-02 22:56
@DomiStyle not sure if we have the same issue, with mine the video doesn't actually start playing, it just loads infinitely without showing the loading circle.

**Comment by DomiStyle** [comment] 2017-11-02 23:02
@dkanada So it's just the blank player ontop of the the backdrop?

Did you try with Firefox 57? You didn't disable the OpenH264 plugin by accident?

**Comment by LukePulverenti** [comment] 2017-11-19 21:04
Have you tried this in Firefox Quantum? I have not been able to reproduce this.

**Comment by LukePulverenti** [comment] 2017-11-22 05:55
Closing as I'm unable to reproduce. If you run into this with the new server release, 3.2.40, please let us know. Thanks.

**Closed by LukePulverenti** 2017-11-22 05:55 UTC
Labels: bug
