### ISSUE TITLE
Use LabelSeasonFolderPattern when detecting seasons (or create a new field for it)

### ISSUE THREAD

**Issue by elboletaire** [MediaBrowser/Emby#1614] opened 2016-04-01 09:07 UTC
I've recently reset my emby database (it was very buggy and resetting the db seems to be worked) and now I need to redefine every season because emby is unable to detect my season namings.

I have some tv series using  `Season ([0-9]+)` and they work, but most of them are defined as `([0-9]+)a Temporada` and that's not automatically detected by emby.

Under `Auto-Organize` we can define the season folder pattern and that could be used when detecting new seasons, but it's only used when Auto-Organizing.

Could you use that when detecting seasons? If not, could you define a new field for this?

**Comment by LukePulverenti** [comment] 2016-04-02 03:55
Duplicate of #1139 - https://github.com/MediaBrowser/Emby/issues/1139

**Closed by LukePulverenti** 2016-04-02 03:55 UTC

**Comment by elboletaire** [comment] 2016-04-02 10:51
Ok, but not directly to the issue. More related to [the second comment](https://github.com/MediaBrowser/Emby/issues/1139#issuecomment-122554170).

**Comment by elboletaire** [comment] 2016-04-04 14:25
In fact... they speak about "Episode Expressions" not "Season Expressions" that is what I'm asking for here.

Shouldn't be in a separate issue?

**Comment by elboletaire** [comment] 2016-04-07 18:06
@LukePulverenti sorry to tag you just for this, but it seems you are not receiving notifications after the issue has been closed.
