### ISSUE TITLE
Webinterface do not play every song in queue

### ISSUE THREAD

**Issue by CordlessWool** [MediaBrowser/Emby#3069] opened 2017-12-12 19:21 UTC
I am listen to audiobooks in the webinterface and some times it jumps over some files. When I click on the file, it jumps to a file later. Only if I click right and say there play it plays the file but every thing else do not work. If i control kodi via the webinterface I did not recognized any issue right now.

I am using the docker container and emby is at latest version (3.2.50.0).

**Comment by LukePulverenti** [comment] 2017-12-12 20:58
Hi, does the browser console show any errors? can you capture the console output? thanks.

**Comment by CordlessWool** [comment] 2017-12-16 19:13
I had the same problem with the android app. But it is different from time to time. Write now I do not a special record for the problem. But last time I want to reproduce it, it does not occur. But I will look up if the error happens next time

**Comment by LukePulverenti** [comment] 2017-12-21 02:18
Hi, can you reproduce this on 3.2.60? Nothing specific was done but I am just curious to see where things stand. Thanks.

**Comment by LukePulverenti** [comment] 2018-01-14 06:31
Closing due to abandonment, but please feel free to re-open if there is still a reproducible issue. Thanks.

**Closed by LukePulverenti** 2018-01-14 06:31 UTC
Labels: bug

**Comment by CordlessWool** [comment] 2018-01-29 20:32
Ok, write now I did not find time to test it again, mostly i the server to watch movies.
