### ISSUE TITLE
Some Hebrew subtitles characters display as squares

### ISSUE THREAD

**Issue by rotem925** [MediaBrowser/Emby#3499] opened 2018-12-28 17:15 UTC
It appears that some(only some) of the subtitles that have been downloaded by Emby appears as square characters. Usually, it happens with the ל and כ character.

It happens to me on an Android phone.
On Chrome browser, the subtitles display just fine. 
I have the latest emby stable version installed 3.5.3.0.

Attached is a screenshot and the srt file:

[Grease.1978.720p.BluRay.x264-x0r.heb.srt.zip](https://github.com/MediaBrowser/Emby/files/2715286/Grease.1978.720p.BluRay.x264-x0r.heb.srt.zip)

![screenshot_20181228-185616_emby](https://user-images.githubusercontent.com/248898/50522666-c969a800-0ad4-11e9-80a6-ece8cc228f2a.jpg)

**Comment by LukePulverenti** [comment] 2018-12-31 03:08
Hi, thanks for the report. I'm closing this as a duplicate of #3399 Hebrew Subtitles - Weird behaviour in multiple devices. When working on this, we'll utilize the information from both tickets. Thanks !

**Closed as completed by LukePulverenti** 2018-12-31 03:08 UTC
