### ISSUE TITLE
[Bug] Sometimes EMBY server keeps running on the background even after closing the application from tray.

### ISSUE THREAD

**Issue by TahminRomit** [MediaBrowser/Emby#3696] opened 2021-08-09 04:37 UTC
![image](https://user-images.githubusercontent.com/83645920/128660548-eaa728e8-2b6d-4959-890d-db04cd264042.png)
Hitting exit does not always close embyserver.exe, it only closes the embytray.exe (you can see that there's no embytray.exe on the inserted image taken from task manager). The server is accessible from clients and EMBY is not visible on tray icon

system: Windows 10 operating system
EMBY server version: 4.6.4 (latest)

I am adding my last embyserver.txt found on logs for additional information, I am actually kinda noob in bug reporting so it may help you.
[embyserver.txt](https://github.com/MediaBrowser/Emby/files/6952141/embyserver.txt)

**Comment by LukePulverenti** [comment] 2021-08-16 16:40
Hi, can you please try removing the statistics plugin, then restart the server and see if the issue persists? Thanks.

**Comment by LukePulverenti** [comment] 2021-12-01 20:46
@RomitBD  has this helped?

**Comment by LukePulverenti** [comment] 2022-07-14 19:09
Closing, unable to reproduce. But please feel free to re-open with the requested information. Thanks.

**Closed as completed by LukePulverenti** 2022-07-14 19:09 UTC
