### ISSUE TITLE
Feedback: Add WD My Cloud Support.

### ISSUE THREAD

**Issue by trilleplay** [MediaBrowser/Emby#2718] opened 2017-06-21 16:49 UTC
I think you should add support for WD My Cloud.
This would expand your current NAS availability !

**Comment by LukePulverenti** [comment] 2017-06-21 18:40
Duplicate of #2015

**Closed by LukePulverenti** 2017-06-21 18:40 UTC

**Comment by LukePulverenti** [comment] 2018-06-03 17:13
You can participate in testing here: https://emby.media/community/index.php?/topic/59597-emby-server-for-western-digital-nas/

Thanks guys.
