### ISSUE TITLE
dot-filenames get picked up by emby server

### ISSUE THREAD

**Issue by mikaelmoutakis** [MediaBrowser/Emby#1392] opened 2016-01-06 15:03 UTC
I'm using server version 3.0.5781.8 on FreeNAS. My media-collection is exposed to OS X using SMB. The media scanner picks up names that start with an dot. OS X sometimes produces a metadata file with the same name as the media file, but with an dot appendend in the beginning. Example:

mmo@Mikaels-MacBook-Pro-2 /V/v/f/L'avventura (1960)> ls -alt
total 2292316
drwx------  1 mmo  344714337       16384  6 Jan 02:55 ..
drwx------  1 mmo  344714337       16384 17 Maj  2015 .
-rwx------  1 mmo  344714337         368 17 Maj  2015 ._L'AVVENTURA 480p.mp4
-rwx------  1 mmo  344714337  1173631091 15 Maj  2015 L'AVVENTURA 480p.mp4

Emby then picks up both files, creating a double entry of this film.

**Comment by kpeterson11** [comment] 2016-01-20 20:06
I'm seeing this on 5786.0 as well.  The problem is the ._* files get picked up by emby when they should be ignored.

**Comment by LukePulverenti** [comment] 2016-01-22 04:42
The fix for this is in the dev branch. It's just not being merged forward until other changes are ready to be as well.

**Comment by LukePulverenti** [comment] 2016-02-09 18:14
This is also available in the beta branch now.

**Comment by LukePulverenti** [comment] 2016-02-22 04:47
This is in the stable release now.

**Closed by LukePulverenti** 2016-02-22 04:47 UTC

**Comment by mikaelmoutakis** [comment] 2016-02-22 11:17
Thanks a lot! Will test
