### ISSUE TITLE
EmbyReports - Menu overlap

### ISSUE THREAD

**Issue by 42bios** [MediaBrowser/Emby#3602] opened 2020-02-24 18:24 UTC
Hi, nope sorry. Problem still exists ...  :/
edit: Already tried reinstalling on another device, same problem.

<a href="https://abload.de/img/bildschirmfoto2020-027kkje.png"><img src="https://abload.de/img/bildschirmfoto2020-027kkje.png" /></a>

_Originally posted by @42bios in https://github.com/MediaBrowser/Emby/issues/3571#issuecomment-590096036_

**Comment by LukePulverenti** [comment] 2020-03-03 18:10
Duplicate of: https://github.com/MediaBrowser/EmbyReports/issues/12

**Closed as completed by LukePulverenti** 2020-03-03 18:10 UTC
