### ISSUE TITLE
[BEHAVIOR][WEB UI] Episode horizontal scroll

### ISSUE THREAD

**Issue by mikafouenski** [MediaBrowser/Emby#3275] opened 2018-05-16 14:48 UTC
Hello,
Is it normal that in the web interface all episodes scrolls have "scroll pass the end" behavior ?

### How to see what I'm talking about : 
- Go to the home page
- Click next on any slider multiples times

### Wanted behavior
When the slider reach the end just stop sliding. ^^

---
Can you clarify ? Is this wanted for any reason ?

Anyway this is really great software :+1: 
Mickaël

**Comment by LukePulverenti** [comment] 2018-05-16 16:43
Hi, it's not by design, it's just an open issue on desktop layouts right now. Thanks.

**Comment by HRSCR** [comment] 2018-07-21 17:29
Luke, It was addressed in 3.6.0.2 beta, or still in process? Thanks

**Comment by LukePulverenti** [comment] 2019-07-25 04:43
This will be resolved in Emby Server 4.2 for Firefox, and all Chromium based browsers such as Chrome, Opera, etc. It will still be an open issue for MacOS Safari.

**Comment by LukePulverenti** [comment] 2020-02-11 01:13
Resolved for Emby Server 4.4.

**Closed by LukePulverenti** 2020-02-11 01:13 UTC
Labels: bug
