### ISSUE TITLE
DLNA problems

### ISSUE THREAD

**Issue by KristupasSavickas** [MediaBrowser/Emby#3349] opened 2018-07-05 15:59 UTC
Here are some of the issues I encountered when using DLNA:

- A lot of times there's a disconnect between what's playing and what's shown on emby. For example, when songs switch (either manually or automatically) the old one remains shown for quite some time (sometimes even minutes). Also the time is horribly out of sync.

- Sometimes, when starting an album the first song plays and playback stops right after. It starts playing pretty much instantaneously when done manually, so I presume it was downloaded to the device. I'll try to get some logs on this

- Queued songs cannot be seen inside the "Remote control" when listening to an album or a playlist . Here's what it looks when playing back locally:
 ![image](https://user-images.githubusercontent.com/1362643/42333939-c6d8b336-8084-11e8-92d6-40997bcd1b0c.png)
 And this is with dlna:
 ![image](https://user-images.githubusercontent.com/1362643/42333881-9a1bf0ba-8084-11e8-8113-53aab6ccaf2b.png)

**Comment by LukePulverenti** [comment] 2018-07-11 16:08
Duplicate of #2442 No playqueue

**Closed by LukePulverenti** 2018-07-11 16:08 UTC
