### ISSUE TITLE
Bug feedback, subtitle bomb, after refreshing the media database, subtitles will be automatically downloaded repeatedly.

### ISSUE THREAD

**Issue by love768952693** [MediaBrowser/Emby#3740] opened 2022-05-24 19:31 UTC
Bug feedback, subtitle bomb, subtitles will be automatically downloaded after refreshing the media database.
Every time you refresh the media database, subtitles will be downloaded repeatedly.

Synology NAS 918  7.X
Update to the latest version: 4.7.0.60, which also has this problem.

Like this
XXX.1.srt
XXX.2.srt
..........
XXX.788.srt

**Comment by LukePulverenti** [comment] 2022-05-24 19:42
Hi there, please provide a specific example and attach the corresponding emby server log. Thanks.

**Comment by LukePulverenti** [comment] 2022-07-14 19:14
Closing, unable to reproduce. But please feel free to re-open with the requested information. Thanks.

**Closed as completed by LukePulverenti** 2022-07-14 19:14 UTC
