### ISSUE TITLE
[Bug] Chromecast playback stops - skips to next playlist item

### ISSUE THREAD

**Issue by bitodt** [MediaBrowser/Emby#3678] opened 2021-03-15 13:33 UTC
When casting to chromecast, some films & series will stop at about 2 minutes of play time.
Films just stop playing.
Series skip to the next episode, as if the current one finished.

Look at these [ffmpeg logs ](https://pastebin.com/qbx5PGis), we can see a received exit command for some reason. 

Setup: docker image linuxserver/emby:4.6.0.4-ls64 running on debian server.
Playback works flawlessly on pc browser and android client, so I assume it has to do with transcoding...

**Comment by LukePulverenti** [comment] 2021-06-23 16:52
HI, are you still running into this with Emby Server 4.6.3?

**Comment by LukePulverenti** [comment] 2022-07-14 19:08
Closing, unable to reproduce. But please feel free to re-open with the requested information. Thanks.

**Closed as completed by LukePulverenti** 2022-07-14 19:08 UTC
