### ISSUE TITLE
[Request] Note to admin / Message form user

### ISSUE THREAD

**Issue by mashranga** [MediaBrowser/Emby#2290] opened 2016-11-15 03:12 UTC
It will be great, if there will be feature like user can request for any media / write any note to admin.

**Comment by SvenVandenbrande** [comment] 2016-11-21 21:03
@LukePulverenti You can close this one...

Duplicate --> https://github.com/MediaBrowser/Emby/issues/1634

**Comment by LukePulverenti** [comment] 2016-11-30 19:57
Duplicate of #1634

**Closed by LukePulverenti** 2016-11-30 19:57 UTC
