### ISSUE TITLE
Unnecessary downloading of subtitles

### ISSUE THREAD

**Issue by AdmiralAnimE** [MediaBrowser/Emby#2947] opened 2017-10-08 21:30 UTC
I had set downloading of subtitles that match my videos and skip if audio or embedded are the same language, but I already have files in the foldes of some shows. They are properly named, but I noticed that where Emby managed to find matching subtitles, it downloaded them despite my files. The new files are basically the same as mine, just with a different extension. I think I have .sub and it downloaded .srt copies, so I disabled it. Can I set it to always prefer the subtitles I have, if available? It supports the formats, so why is it ignoring them?

**Comment by LukePulverenti** [comment] 2017-10-08 22:27
Are they named with the language? Without this the server doesn't know what the language is and that is why the downloading is happening. You can learn how to name your subtitles with the language here:

https://github.com/MediaBrowser/Wiki/wiki/Subtitles

Thanks.

**Comment by AdmiralAnimE** [comment] 2017-10-09 04:59
Yes, they have the short language at the end of the file name.

**Comment by LukePulverenti** [comment] 2017-10-10 14:14
Can you discuss an example? thanks.

**Comment by LukePulverenti** [comment] 2017-10-14 18:03
Any example? thanks.

**Comment by AdmiralAnimE** [comment] 2017-10-17 10:19
Sorry, I was away. What example exactly do you want? Last time I tried it it downloaded .srt of one episode of a season, even when the entire season has .sub files named properly.

**Comment by AdmiralAnimE** [comment] 2017-10-20 10:24
![asda](https://user-images.githubusercontent.com/6396538/31816396-dd46b7ce-b598-11e7-8bd6-d51817bf3877.jpg) Is this what you wanted?
All my episodes are in this format, some without the name. The downloaded subtitles are correct both in name and content, just not necessary. I also have folders "extras" in the seasons, but I guess it's not supported like for movies? Because emby is listing half of the extras, then half of the episodes are listed two times, with the first link playing an extra.

**Comment by LukePulverenti** [comment] 2017-10-20 15:44
no, the media info from the detail screen. thanks.

**Comment by AdmiralAnimE** [comment] 2017-10-21 04:41
![asdas](https://user-images.githubusercontent.com/6396538/31848085-d6670cf2-b632-11e7-8d53-da1428dab77e.jpg)

**Comment by LukePulverenti** [comment] 2017-10-21 04:46
No, this is the metadata editor. I mean the media info at the bottom of the detail screen in the web app. The same screen where you would play the video.

**Comment by AdmiralAnimE** [comment] 2017-10-21 07:43
Stats for nerds?

**Comment by LukePulverenti** [comment] 2017-10-21 16:20
Click on the item in the web app and that will open up the detail screen. thanks.

**Comment by AdmiralAnimE** [comment] 2017-10-21 17:53
![2017-10-21 20 52 02-fullpage](https://user-images.githubusercontent.com/6396538/31854432-d0502b0e-b6a1-11e7-8039-8f25806a1cfe.jpg)

**Comment by LukePulverenti** [comment] 2017-10-21 17:54
That is a series folder. Can we look at an actual video file example? thanks.

**Comment by AdmiralAnimE** [comment] 2017-10-22 04:41
Yes.. I never thought to click on that little icon.
![asdasdw](https://user-images.githubusercontent.com/6396538/31858270-415d45b6-b6fc-11e7-8acf-5029275eb250.jpg)

**Comment by LukePulverenti** [comment] 2017-10-22 04:47
And what are your subtitle download settings?

**Comment by AdmiralAnimE** [comment] 2017-10-22 13:07
![gweag](https://user-images.githubusercontent.com/6396538/31862224-fe4a1316-b742-11e7-9348-da508395ca4e.jpg)

**Comment by LukePulverenti** [comment] 2017-10-22 19:36
Ok, as presently constructed it is working as designed, although I can see how that would be unclear to you.

The reason it downloads SRT even though you already have .sub is because .sub files are graphic subtitles, and these will require server transcoding for many apps such as the web app, Roku, Smart TV's, etc.

The subtitle download feature has two goals - to not only help you obtain subtitles, but also to help you ensure you have text-based versions that can be delivered to Emby apps more efficiently.

**Comment by AdmiralAnimE** [comment] 2017-10-22 19:58
Thanks, I didn't know that. Can you add an option to somehow change that behaviour? I will try to find a converter for the subtitles, but it would be better to have a choice.

**Comment by LukePulverenti** [comment] 2017-10-24 05:33
Yes it's a possibility for the future. Closing this for now, will re-word the help text on the config screen.

**Closed by LukePulverenti** 2017-10-24 05:33 UTC
