### ISSUE TITLE
[IDEA] Making it possible to utilize an external database (MySQL / PostreSQL / ??)

### ISSUE THREAD

**Issue by karbowiak** [MediaBrowser/Emby#1296] opened 2015-12-03 00:23 UTC
If possible, add in a way to utilize an external database, since SQLite can get bogged down easily if you have a massive amount of data.

Which some users (a lot?) have. Plus more performance is never bad.

**Comment by LukePulverenti** [comment] 2015-12-06 17:22
Duplicate of #1122

**Closed by LukePulverenti** 2015-12-06 17:22 UTC
