### ISSUE TITLE
Identification

### ISSUE THREAD

**Issue by Al4ndil** [MediaBrowser/Emby#3670] opened 2021-01-18 08:46 UTC
Hi,

I don't know how to pull a new request.

when we identify a media and the result of the search is not suitable, it would be interesting to allow the search to be relaunched with the "Back" arrow

Also it will be nice to have more results for the search. :)

Thx

**Comment by nomandera** [comment] 2021-01-18 11:02
This may be related to an issue I have been looking at but cant have repeated by others yet and as such have not reported (assumed it was a issue of my install)

Scenario setup:

- Search for a word
- Select a result from the `filtered results` to look at the detailed view
- Click back
- You are returned to the  `filtered results` page
- Select another result (even the same one you chose above)
- Click back
- You are returned to the Emby Home page and not the `filtered results` page

**Comment by LukePulverenti** [comment] 2021-01-18 18:10
Duplicate of #3496.

**Closed as completed by LukePulverenti** 2021-01-18 18:10 UTC
