### ISSUE TITLE
[REQ] Ability to bind Emby to a user specified IP

### ISSUE THREAD

**Issue by karbowiak** [MediaBrowser/Emby#1327] opened 2015-12-18 14:10 UTC
Essentially being able to tell it to listen on a specific IP, instead of whatever IP it decided at runtime, which on some setups can be the completely wrong IP to listen on..

Or for those of us who use nginx/apache as a relay, and want Emby to be on 127.0.0.1.

**Comment by LukePulverenti** [comment] 2015-12-24 18:48
duplicate of #1302 

If this is meant to be separate - the http server binds to IpAny, which means it handles requests to the 8096 port on any address supported by the system.

**Closed by LukePulverenti** 2015-12-24 18:48 UTC
