### ISSUE TITLE
Unable to correctly run MediaBrowser.ServerApplication on a fresh clone

### ISSUE THREAD

**Issue by AeonLucid** [MediaBrowser/Emby#3026] opened 2017-11-19 20:34 UTC
I want to try and work a bit on Emby but I have trouble getting it even to run at all.

Steps to reproduce.

1. Clone the repository in a fresh directory.
2. Start up VS2017 using `MediaBrowser.sln`.
3. Select `MediaBrowser.ServerApplication` as startup project.
4. Press `Start`.

**Comment by LukePulverenti** [comment] 2017-11-19 20:48
hi, it works fine here. what actually happens?

**Comment by AeonLucid** [comment] 2017-11-19 21:52
@LukePulverenti It starts with this:

```
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Users\Mike\Documents\Repositories\Emby\ProgramData-Server\transcoding-temp'.'
```

If I create that directory, this happens:

```
System.IO.FileNotFoundException: 'Could not find file 'C:\Users\Mike\Documents\Repositories\Emby\ProgramData-Server\data\connect.txt'.'
```

Then I copy that file from my normal Emby installation and it keeps going until all files are there.
It fails to initialize the programdata directory somehow.

**Comment by LukePulverenti** [comment] 2017-11-20 00:17
Can you attach the complete log file? what versions of the .net framework do you have installed?

**Comment by AeonLucid** [comment] 2017-11-20 00:42
**Logs**
- [server-63646738529.txt](https://github.com/MediaBrowser/Emby/files/1486150/server-63646738529.txt)
- [vsstudio-output.txt](https://github.com/MediaBrowser/Emby/files/1486152/vsstudio-output.txt)

**Versions**
- [Net Framework](https://user-images.githubusercontent.com/4643257/32997700-b8af2fdc-cd93-11e7-83e0-5a5df3c9f83c.png)
- [vcredist](https://user-images.githubusercontent.com/4643257/32997706-d9739078-cd93-11e7-818e-21e55f52c838.png)

**Note:** Running an Emby release (ex; https://github.com/MediaBrowser/Emby/releases/download/3.2.36.0/embyserver-win-x64-3.2.36.0.7z) works fine on the same PC.

**Comment by LukePulverenti** [comment] 2017-11-30 18:30
Tested on windows 10 in debug mode, no problem found. I will need to close this as I cannot reproduce. Please feel free to reopen if you can investigate more and find out what is going on. Thanks.

**Closed by LukePulverenti** 2017-11-30 18:30 UTC
Labels: bug

**Comment by AeonLucid** [comment] 2017-12-01 19:19
@LukePulverenti Still happens for me on Windows 10 x64 with VS2017 (+ ReSharper).
