### ISSUE TITLE
Support audio podcasts in Web Interface

### ISSUE THREAD

**Issue by marmay** [MediaBrowser/Emby#2693] opened 2017-06-08 06:42 UTC
According to #528, video podcasts in the web interface work, but audio podcasts do not. This corresponds with my own observations.

I think, this is a *bug*, because the user interface gives the impression that audio podcasts should work, but fails silently. I think the bug can be fixed in several ways:

- by emitting an error message to the server log
- by showing an error in the web interface
- by supporting audio podcasts properly

I tried with several podcasts, including the TED podcast that was listed as working somewhere in the forums. A similar problem that might be related happens when using the TuneIn plugin.

---

I'm opening this issue for two reasons:
1. I want to confirm that the problem still exists and is not related to my set up,
2. If it is no priority for the dev team, I might want to fix that problem myself, if I can.

**Comment by LukePulverenti** [comment] 2017-06-08 13:03
Can you give an example podcast? thanks.

**Comment by marmay** [comment] 2017-06-08 13:13
An example of an audio podcast that does not work:
http://www1.swr.de/podcast/xml/swr1/bw/leute.xml
and a video podcast that does work:
http://www1.swr.de/podcast/xml/swr1/bw/leute-video.xml

(same provider and content in order to illustrate the issue)

**Comment by chepec** [comment] 2017-07-11 21:27
I think I can add some more observations. Just installed the release version of the Podcasts plugin (v. 1.0.6287.42903), and added a few feeds using the nice new interface. 

Running the "Refresh channels" scheduled task looks OK (showing the log output):

```
2017-07-11 23:24:29.7219 Info TaskManager: Executing Refresh Channels
2017-07-11 23:24:29.7219 Info HttpServer: HTTP Response 204 to 192.168.1.1. Time: 2ms. http://emby.xyz:8096/ScheduledTasks/Running/a27c54259520b2e5c509def68c8f4c45 
2017-07-11 23:24:29.7258 Info HttpClient: HttpClientManager GET: https://geeksguideshow.com/feed/
2017-07-11 23:24:29.7266 Info HttpServer: HTTP GET http://emby.xyz:8096/ScheduledTasks?isHidden=false. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2017-07-11 23:24:29.7286 Info HttpServer: HTTP Response 200 to 192.168.1.1. Time: 2ms. http://emby.xyz:8096/ScheduledTasks?isHidden=false 
2017-07-11 23:24:30.1576 Info HttpClient: HttpClientManager GET: http://chemistryworld.libsyn.com/magazine
2017-07-11 23:24:30.6242 Info HttpClient: HttpClientManager GET: http://chemistryinitselement.libsyn.com/rss
2017-07-11 23:24:31.6759 Info HttpClient: HttpClientManager GET: http://chemistryworldbookclub.libsyn.com/BookClub
2017-07-11 23:24:32.9606 Info HttpClient: HttpClientManager GET: http://podcasts.files.bbci.co.uk/b07dx75g.rss
2017-07-11 23:24:33.0411 Info HttpClient: HttpClientManager GET: http://feeds.99percentinvisible.org/99percentinvisible
2017-07-11 23:24:33.2460 Info HttpClient: HttpClientManager GET: https://geeksguideshow.com/feed/
2017-07-11 23:24:33.4874 Info HttpClient: HttpClientManager GET: http://chemistryworld.libsyn.com/magazine
2017-07-11 23:24:33.8980 Info HttpClient: HttpClientManager GET: http://chemistryinitselement.libsyn.com/rss
2017-07-11 23:24:35.1966 Info HttpClient: HttpClientManager GET: http://chemistryworldbookclub.libsyn.com/BookClub
2017-07-11 23:24:36.5248 Info HttpClient: HttpClientManager GET: http://podcasts.files.bbci.co.uk/b07dx75g.rss
2017-07-11 23:24:36.5956 Info HttpClient: HttpClientManager GET: http://feeds.99percentinvisible.org/99percentinvisible
2017-07-11 23:24:53.2739 Info TaskManager: Refresh Channels Completed after 0 minute(s) and 23 seconds
2017-07-11 23:24:53.2753 Info ServerManager: Sending web socket message ScheduledTaskEnded
2017-07-11 23:24:53.2753 Info TaskManager: ExecuteQueuedTasks
```

Trying to play a podcast episode is where it gets bad. I tried to play from both the emby web ui in Chrome (on latest Debian as well as Ubuntu) and from the Emby Android app. Neither work, and the log output looks identical. (Also tried playing while logged in as the admin user, just in case the regular user had some restriction.)

```
2017-07-11 23:14:48.6394 Info HttpServer: HTTP HEAD http://emby.xyz:8096/Audio/67d84f9667a6465702f73fbbd4595cf7/universal?UserId=66cd969b22b54891a7576b9581f8e0ae&DeviceId=a72eef548233bf6b3e09b3b25c671828383c8cdb&MaxStreamingBitrate=914285714&Container=opus,mp3,aac,m4a,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1499802890855&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2017-07-11 23:14:48.6422 Info App: User policy for admin. EnableAudioPlaybackTranscoding: True
2017-07-11 23:14:48.6422 Info App: Profile: Unknown Profile, No direct play profiles found for Path: http://traffic.libsyn.com/chemistryworldbookclub/The_death_of_expertise.mp3?dest-id=403628
2017-07-11 23:14:48.6428 Info HttpServer: HTTP Response 302 to 192.168.1.1. Time: 4ms. http://emby.xyz:8096/Audio/67d84f9667a6465702f73fbbd4595cf7/universal?UserId=66cd969b22b54891a7576b9581f8e0ae&DeviceId=a72eef548233bf6b3e09b3b25c671828383c8cdb&MaxStreamingBitrate=914285714&Container=opus,mp3,aac,m4a,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1499802890855&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=true 
2017-07-11 23:14:48.6511 Info HttpServer: HTTP GET http://emby.xyz:8096/Audio/67d84f9667a6465702f73fbbd4595cf7/universal?UserId=66cd969b22b54891a7576b9581f8e0ae&DeviceId=a72eef548233bf6b3e09b3b25c671828383c8cdb&MaxStreamingBitrate=914285714&Container=opus,mp3,aac,m4a,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1499802890855&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=true. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2017-07-11 23:14:48.6532 Info App: User policy for admin. EnableAudioPlaybackTranscoding: True
2017-07-11 23:14:48.6532 Info App: Profile: Unknown Profile, No direct play profiles found for Path: http://traffic.libsyn.com/chemistryworldbookclub/The_death_of_expertise.mp3?dest-id=403628
2017-07-11 23:14:48.6532 Info HttpServer: HTTP Response 302 to 192.168.1.1. Time: 3ms. http://emby.xyz:8096/Audio/67d84f9667a6465702f73fbbd4595cf7/universal?UserId=66cd969b22b54891a7576b9581f8e0ae&DeviceId=a72eef548233bf6b3e09b3b25c671828383c8cdb&MaxStreamingBitrate=914285714&Container=opus,mp3,aac,m4a,flac,webma,webm,wav,ogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&PlaySessionId=1499802890855&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=true 
2017-07-11 23:14:48.8985 Info HttpServer: HTTP POST http://emby.xyz:8096/Sessions/Playing. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2017-07-11 23:14:48.9061 Info HttpServer: HTTP Response 204 to 192.168.1.1. Time: 8ms. http://emby.xyz:8096/Sessions/Playing 
2017-07-11 23:14:48.9092 Info HttpServer: HTTP POST http://emby.xyz:8096/Sessions/Playing/Progress. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2017-07-11 23:14:48.9102 Info HttpServer: HTTP POST http://emby.xyz:8096/Sessions/Playing/Progress. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2017-07-11 23:14:48.9129 Info HttpServer: HTTP Response 204 to 192.168.1.1. Time: 4ms. http://emby.xyz:8096/Sessions/Playing/Progress 
2017-07-11 23:14:48.9142 Info HttpServer: HTTP Response 204 to 192.168.1.1. Time: 4ms. http://emby.xyz:8096/Sessions/Playing/Progress 
2017-07-11 23:14:48.9986 Info HttpServer: HTTP POST http://emby.xyz:8096/Sessions/Playing/Stopped. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2017-07-11 23:14:48.9999 Info SessionManager: Playback stopped reported by app Emby Mobile 3.2.25.0 playing The death of expertise. Stopped at 0 ms
2017-07-11 23:14:49.0033 Info HttpServer: HTTP Response 204 to 192.168.1.1. Time: 5ms. http://emby.xyz:8096/Sessions/Playing/Stopped 
```

The web UI just flickers briefly, then shows the episode marked as viewed. The log indicates HTTP error 204 ("no content") as well as the line `Info App: Profile: Unknown Profile, No direct play profiles found for Path: <URL to episode>`, which looks like an interesting starting point for a bug hunt. But what do I know ;-)

Sadly, the current version of the Podcast plugin is useless for audio podcasts. I hope the log excerpts above can help in pinpointing the cause of this bug, which does not seem related to any particular feed (I tested five or six feeds, and many different episodes).

**Comment by LukePulverenti** [comment] 2017-07-11 21:54
It is direct playing to the url and depending on the remote server policy for access control headers that is dictating whether it plays or not. Video is working because we have an automatic switch to server transcoding in the event of a failure, but we have not yet added that feature for audio playback.

**Comment by develroo** [comment] 2017-08-02 15:10
> It  is direct playing to the url and depending on the remote server policy  for access control headers that is dictating whether it plays or not.  Video is working because we have an automatic switch to server  transcoding in the event of a failure, but we have not yet added that  feature for audio playback.


Any progress on this? Approximately 70% of all web podcasts are audio or audio supported. That is a significant number of podcasts that are unable to be played via the plugin.

**Comment by LukePulverenti** [comment] 2017-09-07 19:46
Resolved for next release.

**Closed by LukePulverenti** 2017-09-07 19:46 UTC
