### ISSUE TITLE
BUG:IOS APP problem

### ISSUE THREAD

**Issue by jonnyman12345** [MediaBrowser/Emby#3621] opened 2020-05-30 06:01 UTC
After you select subtitles, the screen is out of control。

**Comment by LukePulverenti** [comment] 2020-07-26 16:46
HI there, what do you mean exactly? What version of iOS?

**Comment by LukePulverenti** [comment] 2020-11-18 02:25
Hi there, closing, but I'm not able to reproduce this, so please try the latest version. Please feel free to re-open if you'd like to continue troubleshooting. Thanks.

**Closed as completed by LukePulverenti** 2020-11-18 02:25 UTC
