### ISSUE TITLE
Library Folder mistake when delete same folder in different drives

### ISSUE THREAD

**Issue by RafaG** [MediaBrowser/Emby#3110] opened 2018-01-05 07:53 UTC
Step to recreate:

Create a Library.
Add folder "Y:\Films\Test 1"
Add folder "X:\Films\Test 1"
Delete "Y:\Films\Test 1"
The app delete the folder "X:\Films\Test 1"

I see this problem more times in other occasions because I have more than one drive and I share the same folder structure in the disks, but with this simple example I think you can find the problem. I'm ussing server version 3.2.60.0 on Win64.

Regards,

**Comment by leonstrife** [comment] 2018-01-08 10:07
v3.26, Windows 64
I ran into similar problems today so I tested it for a while also. I found out not only folder with the same name could have raise the problem. For example, I tried adding three folders on the same drive. And then, when I clicked on to delete the first folder on top, it turned to delete the 2nd or 3rd folder instead.

**Comment by RafaG** [comment] 2018-01-08 17:59
Yes, I think that the problem is not only related to my example, as I mention in my message, I see the problem in other occasions and I think is more general, but I put only one example that is easy to reproduce for developers.

If I remember well, I follow the problem from version 3.2.33.

**Comment by LukePulverenti** [comment] 2018-01-15 03:33
Hi, since you can reproduce this, can you please try the following. Open the library editor for a library that has more than one path.

Instead of clicking the Remove button, just click on the text of one of the folder paths. When you do this, it will show another window. Does this window display the correct path, or not? Thanks !

**Comment by LukePulverenti** [comment] 2018-01-17 19:54
Perfect, thank you. So that confirms that the directory picker chooses the right value, but the remove button does not. Even though I'm not able to reproduce this, I should be able to hunt down the differences. Thanks !

**Comment by LukePulverenti** [comment] 2018-01-19 06:24
Please try with the new 3.2.70 release. thanks.

**Comment by RafaG** [comment] 2018-01-20 15:14
I cant upgrade now the server, I'll try in a few days, I'll inform you.

**Comment by LukePulverenti** [comment] 2018-01-23 07:17
Ok, closing this. Please re-open if there is still an issue. Thanks.

**Closed by LukePulverenti** 2018-01-23 07:17 UTC

**Comment by RafaG** [comment] 2018-01-31 11:12
Hi,

I check today this problem with version 3.2.70 and it seem work perfect. Thanks. This issue can stay close and if you wish, you can update your change logs to inform about this improvement.

Thanks and best regards,
