### ISSUE TITLE
Video overlay sticks when the episode is changed

### ISSUE THREAD

**Issue by DragonEmbers** [MediaBrowser/Emby#3650] opened 2020-11-11 20:01 UTC
When watching a multi-episode series the video control overlay gets stuck on once the episode changes and remains until some user interaction is performed (eg change volume, pause+resume, fullscreen toggle).

Emby: 4.5.2.0
Browser: Firefox 82.0.3 (Not repeatable on Edge 44.19041.423.0)
OS: Windows 10 2004

Browser: Firefox-esr (78.4.1esr-1~deb10u1)
OS: Debian 10 (Buster) LXDE

**Comment by LukePulverenti** [comment] 2020-11-18 02:30
Hi, is the second video playing when this happens?

**Comment by DragonEmbers** [comment] 2020-11-18 20:17
Yes it is, that element of it seems to continue to work

**Comment by LukePulverenti** [comment] 2020-12-03 16:46
Ok, please let me know if you're still seeing this with 4.5.3, once you have that. Thanks.

**Comment by DragonEmbers** [comment] 2021-02-07 00:50
Sorry for the late response, I'm still seeing this issue on 4.5.4.0

**Comment by LukePulverenti** [comment] 2021-06-23 16:58
Hi, are you seeing this with Emby Server 4.6.3?

**Comment by LukePulverenti** [comment] 2022-07-14 19:01
Closing, unable to reproduce. But please feel free to re-open with the requested information. Thanks.

**Closed as completed by LukePulverenti** 2022-07-14 19:01 UTC
