### ISSUE TITLE
Symbolic link reports incorrect length in FileSystemMetadata

### ISSUE THREAD

**Issue by orzFly** [MediaBrowser/Emby#3414] opened 2018-08-23 17:32 UTC
For example, I have the following file structure:

```
/Youtube-AFamousUploader/YoutubeId/YoutubeId.mkv
/Youtube-AFamousUploader/YoutubeId/YoutubeId - thumb1.jpg
/Youtube-AFamousUploader/YoutubeId/YoutubeId - thumb2.jpg
/Youtube-AFamousUploader/YoutubeId/YoutubeId.jpg => (symlink to) YoutubeId - thumb2.jpg
```

Emby will correctly pick YoutubeId.png as the primary image for the video. However, in `http://localhost:8086/emby/Items/5dd90c327990a8c471700495608b815d/Images/Primary`, it returns a truncated image:

```
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
Access-Control-Allow-Origin: *
Content-Type: image/jpeg
Accept-Ranges: bytes
transferMode.dlna.org: Interactive
realTimeInfo.dlna.org: DLNA.ORG_TLAG=*
Vary: Accept
ETag: "9a255fa5ff0168b91e322658f74f70ba"
Cache-Control: public
Server: Microsoft-NetCore/2.0, UPnP/1.0 DLNADOC/1.50
Date: Thu, 23 Aug 2018 17:20:09 GMT
Content-Length: 22
Connection: Close

ÿØÿàJFIFÿÛC
```

Content-Length is incorrectly reported. It should be the size of "YoutubeId - thumb2.jpg" instead of the size of the symlink "YoutubeId.jpg". (The length of "YoutubeId - thumb2.jpg" is 22)

**Comment by orzFly** [comment] 2018-08-23 17:39
```
GET /emby/Items/5dd90c327990a8c471700495608b815d/Images/?api_key=.... HTTP/1.1

[
  {
    "ImageType": "Primary",
    "Path": "/Youtube-AFamousUploader/YoutubeId/YoutubeId.jpg",
    "Height": 648,
    "Width": 1036,
    "Size": 22
  }
]
```

**Comment by orzFly** [comment] 2018-08-23 17:45
https://github.com/MediaBrowser/Emby/blob/7136f547109d3bb211790d6e242425708cf8a8b1/Emby.Server.Implementations/IO/SharpCifsFileSystem.cs#L127-L142

I think maybe we should return the target file length for all symbolic links.

**Comment by LukePulverenti** [comment] 2018-08-23 17:48
That code will only matter if you are actually using smb or unc paths, which in the above example it appears that you are not.

**Comment by orzFly** [comment] 2018-08-23 17:51
Sorry. It should be this one:

https://github.com/MediaBrowser/Emby/blob/7136f547109d3bb211790d6e242425708cf8a8b1/Emby.Server.Implementations/IO/ManagedFileSystem.cs#L344

**Comment by LukePulverenti** [comment] 2018-08-23 17:53
Yes OK. Problem is this is supposed to be happening automatically in the netcore runtime, and it isn't, so unfortunately the issue is there. There is an open ticket about this in the corefx repo.

**Comment by orzFly** [comment] 2018-08-23 17:59
https://github.com/dotnet/corefx/issues/26310
https://github.com/dotnet/corefx/issues/25569
https://github.com/dotnet/corefx/issues/24685

Understood. It's also not easy to handle symbolic links on our own.

**Comment by LukePulverenti** [comment] 2018-09-27 03:41
I know that is still an open issue, but because there's not a long we can do besides wait for this to be implemented in the netcore runtime, I am going to close this, just so that we can keep our issue list clean. Thanks.

**Closed by LukePulverenti** 2018-09-27 03:41 UTC
