### ISSUE TITLE
[BUG]Some bug about cover

### ISSUE THREAD

**Issue by wubushanyan** [MediaBrowser/Emby#3778] opened 2023-04-19 12:02 UTC
Enter the TV program and click on the top button as “Genres”. 
You can see the covers of similar automatic collections in many different genres.
**But there will be episodes that shouldn't be there cover.**
**These episodes are set as inaccessible in those users, but users can see the cover of the inaccessible episodes here**

Really need fix it.

**Comment by LukePulverenti** [comment] 2023-08-09 18:56
Duplicate of #3014

**Closed as completed by LukePulverenti** 2023-08-09 18:56 UTC
